services:
  server-prod:
    build:
      context: .
      dockerfile: ./docker/server.prod.dockerfile
    container_name: server-prod
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${SERVER_PORT}"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - .mvn:/app/.mvn
    command: ./mvnw spring-boot:run -Dspring-boot.run.fork=false
