services:
  server-dev:
    build: 
      context: .
      dockerfile: ./docker/server.dev.dockerfile
    container_name: server-dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - .mvn:/app/.mvn
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DEVTOOLS_RESTART_ENABLED: ${SPRING_DEVTOOLS_RESTART_ENABLED}
    command: ./mvnw spring-boot:run -Dspring-boot.run.fork=false
